"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { api, tokenStore } from "@/lib/api";
import { Badge, Card, SectionTitle, Spinner } from "@/components/ui";
import type { Spec, Strategy } from "@/types";

export default function StrategiesPage() {
  const [strategies, setStrategies] = useState<Strategy[] | null>(null);
  const [generating, setGenerating] = useState(false);
  const [candidates, setCandidates] = useState<{ candidate_id: string; spec: Spec }[]>([]);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    try {
      const rows = await api<Strategy[]>("/strategies", { token: tokenStore.get() });
      setStrategies(rows);
    } catch {
      setStrategies([]);
    }
  }

  useEffect(() => {
    load();
  }, []);

  async function generate() {
    setGenerating(true);
    setError(null);
    try {
      const res = await api<{ candidates: { candidate_id: string; spec: Spec }[] }>(
        "/strategies/generate",
        {
          method: "POST",
          token: tokenStore.get(),
          body: {
            prompt: "scalp strategy for " + "EURUSD M5",
            pairs: ["EURUSD"],
            timeframe: "M5",
            provider: "mock",
          },
        }
      );
      setCandidates(res.candidates || []);
    } catch (e) {
      setError(e instanceof Error ? e.message : "generation failed");
    } finally {
      setGenerating(false);
    }
  }

  async function save(spec: Spec) {
    setError(null);
    try {
      await api("/strategies", {
        method: "POST",
        token: tokenStore.get(),
        body: { spec, notes: "Generated by AI architect (mock)" },
      });
      setCandidates([]);
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : "save failed");
    }
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <SectionTitle>Strategy Studio</SectionTitle>
        <button
          onClick={generate}
          disabled={generating}
          className="rounded-lg bg-accent/90 text-bg px-4 py-2 text-sm font-semibold hover:bg-accent disabled:opacity-50"
        >
          {generating ? "Generating…" : "Generate with AI"}
        </button>
      </div>

      {error && <div className="text-sm text-danger mb-4">{error}</div>}

      {candidates.length > 0 && (
        <div className="mb-6 space-y-3">
          <h3 className="text-sm text-text-dim uppercase tracking-wide">Candidates</h3>
          {candidates.map((c) => (
            <Card key={c.candidate_id} className="flex items-center justify-between">
              <div>
                <div className="font-medium">{c.spec.name}</div>
                <div className="text-xs text-text-dim mt-1 line-clamp-2">{c.spec.plain_english_explanation}</div>
                <div className="flex gap-2 mt-2">
                  <Badge label={c.spec.strategy_family} tone="accent" />
                  <Badge label={`${c.spec.entry_rules.length} entries`} />
                  <Badge label={`${c.spec.exit_rules.length} exits`} />
                </div>
              </div>
              <button
                onClick={() => save(c.spec)}
                className="rounded-lg border border-accent text-accent px-3 py-1.5 text-xs hover:bg-accent/10"
              >
                Save
              </button>
            </Card>
          ))}
        </div>
      )}

      <Card title="Saved strategies">
        {!strategies ? (
          <Spinner />
        ) : strategies.length === 0 ? (
          <p className="text-sm text-text-dim">
            No strategies yet. Click <span className="text-accent">Generate with AI</span> to create your first
            hypothesis, or save one via the API.
          </p>
        ) : (
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs text-text-dim border-b border-border">
                <th className="py-2 pr-3">Name</th>
                <th className="py-2 pr-3">Family</th>
                <th className="py-2 pr-3">Version</th>
                <th className="py-2">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {strategies.map((s) => (
                <tr key={s.id} className="hover:bg-panel2/50">
                  <td className="py-2 pr-3">
                    <Link href={`/strategies/${s.id}`} className="text-accent hover:underline">
                      {s.name}
                    </Link>
                  </td>
                  <td className="py-2 pr-3 text-text-dim">{s.strategy_family}</td>
                  <td className="py-2 pr-3 text-text-dim">{s.current_version}</td>
                  <td className="py-2">
                    <Badge label={s.status} tone={s.status === "paper_trading_eligible" ? "good" : "default"} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </Card>
    </div>
  );
}