"""paper live ledger tables and account trading state

Revision ID: 3e53fa76c144
Revises: 6142d2b1d825
Create Date: 2026-08-29 16:37:40.881383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3e53fa76c144'
down_revision = '6142d2b1d825'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_margin_events',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.Column('trading_state', sa.String(length=24), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_margin_events_account_id'), 'paper_margin_events', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_margin_events_ts'), 'paper_margin_events', ['ts'], unique=False)
    op.create_table('paper_orders',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('size_units', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('request_ts', sa.Float(), nullable=False),
    sa.Column('approval_ts', sa.Float(), nullable=True),
    sa.Column('fill_ts', sa.Float(), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_side', sa.String(length=8), nullable=True),
    sa.Column('worker_id', sa.String(length=24), nullable=True),
    sa.Column('rejection_reason', sa.String(length=512), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['paper_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['simulated_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_orders_account_id'), 'paper_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_position_id'), 'paper_orders', ['position_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_request_ts'), 'paper_orders', ['request_ts'], unique=False)
    op.create_index(op.f('ix_paper_orders_strategy_id'), 'paper_orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_paper_orders_trade_id'), 'paper_orders', ['trade_id'], unique=False)
    op.create_table('paper_fills',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('trade_id', sa.String(length=36), nullable=True),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('fill_type', sa.String(length=16), nullable=False),
    sa.Column('spread_cost', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('bid_ask_basis', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['paper_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['simulated_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_fills_account_id'), 'paper_fills', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_order_id'), 'paper_fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_position_id'), 'paper_fills', ['position_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_trade_id'), 'paper_fills', ['trade_id'], unique=False)
    op.create_index(op.f('ix_paper_fills_ts'), 'paper_fills', ['ts'], unique=False)
    op.add_column('paper_accounts', sa.Column('trading_state', sa.String(length=24), server_default='INACTIVE', nullable=False))
    op.add_column('paper_accounts', sa.Column('state_reason', sa.String(length=512), nullable=True))
    op.execute("ALTER TABLE paper_accounts ALTER COLUMN trading_state DROP DEFAULT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_accounts', 'state_reason')
    op.drop_column('paper_accounts', 'trading_state')
    op.drop_index(op.f('ix_paper_fills_ts'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_trade_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_position_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_order_id'), table_name='paper_fills')
    op.drop_index(op.f('ix_paper_fills_account_id'), table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index(op.f('ix_paper_orders_trade_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_strategy_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_request_ts'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_position_id'), table_name='paper_orders')
    op.drop_index(op.f('ix_paper_orders_account_id'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index(op.f('ix_paper_margin_events_ts'), table_name='paper_margin_events')
    op.drop_index(op.f('ix_paper_margin_events_account_id'), table_name='paper_margin_events')
    op.drop_table('paper_margin_events')
    # ### end Alembic commands ###
