"""initial schema

Revision ID: af440c752e5f
Revises: 
Create Date: 2026-08-27 21:09:24.556637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'af440c752e5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', 'ts')
    )
    op.create_table('spreads',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('spread_pips', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spreads_symbol'), 'spreads', ['symbol'], unique=False)
    op.create_index(op.f('ix_spreads_ts'), 'spreads', ['ts'], unique=False)
    op.create_table('ticks',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('ask', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticks_symbol'), 'ticks', ['symbol'], unique=False)
    op.create_index(op.f('ix_ticks_ts'), 'ticks', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_table('alerts',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_workspace_id'), 'alerts', ['workspace_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('immutable', sa.Boolean(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_table('broker_connections',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_api_secret', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_connections_workspace_id'), 'broker_connections', ['workspace_id'], unique=False)
    op.create_table('economic_events',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('event_time', sa.Float(), nullable=False),
    sa.Column('actual', sa.String(length=64), nullable=True),
    sa.Column('forecast', sa.String(length=64), nullable=True),
    sa.Column('previous', sa.String(length=64), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_events_country'), 'economic_events', ['country'], unique=False)
    op.create_index(op.f('ix_economic_events_currency'), 'economic_events', ['currency'], unique=False)
    op.create_index(op.f('ix_economic_events_event_time'), 'economic_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_economic_events_workspace_id'), 'economic_events', ['workspace_id'], unique=False)
    op.create_table('forex_symbols',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('canonical', sa.String(length=32), nullable=False),
    sa.Column('provider_symbol', sa.String(length=64), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('quote_currency', sa.String(length=8), nullable=False),
    sa.Column('pip_position', sa.Integer(), nullable=False),
    sa.Column('pip_value', sa.Float(), nullable=False),
    sa.Column('contract_size', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forex_symbols_canonical'), 'forex_symbols', ['canonical'], unique=False)
    op.create_index(op.f('ix_forex_symbols_provider'), 'forex_symbols', ['provider'], unique=False)
    op.create_index(op.f('ix_forex_symbols_provider_symbol'), 'forex_symbols', ['provider_symbol'], unique=False)
    op.create_index(op.f('ix_forex_symbols_workspace_id'), 'forex_symbols', ['workspace_id'], unique=False)
    op.create_table('market_data_sources',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_sources_workspace_id'), 'market_data_sources', ['workspace_id'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_accounts_workspace_id'), 'paper_accounts', ['workspace_id'], unique=False)
    op.create_table('risk_profiles',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('risk_per_trade_pct', sa.Float(), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Float(), nullable=False),
    sa.Column('max_weekly_loss_pct', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('max_consecutive_losses', sa.Float(), nullable=False),
    sa.Column('max_open_positions', sa.Float(), nullable=False),
    sa.Column('max_trades_per_day', sa.Float(), nullable=False),
    sa.Column('max_correlated_exposure_pct', sa.Float(), nullable=False),
    sa.Column('max_spread_pips', sa.Float(), nullable=False),
    sa.Column('max_slippage_pips', sa.Float(), nullable=False),
    sa.Column('news_blackout_minutes_before', sa.Float(), nullable=False),
    sa.Column('news_blackout_minutes_after', sa.Float(), nullable=False),
    sa.Column('correlated_currency_groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hard_stop_distance_pips', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_profiles_workspace_id'), 'risk_profiles', ['workspace_id'], unique=False)
    op.create_table('saved_chart_layouts',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_chart_layouts_workspace_id'), 'saved_chart_layouts', ['workspace_id'], unique=False)
    op.create_table('strategies',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('strategy_family', sa.String(length=64), nullable=False),
    sa.Column('current_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_name'), 'strategies', ['name'], unique=False)
    op.create_index(op.f('ix_strategies_strategy_family'), 'strategies', ['strategy_family'], unique=False)
    op.create_index(op.f('ix_strategies_workspace_id'), 'strategies', ['workspace_id'], unique=False)
    op.create_table('backtest_jobs',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_jobs_strategy_id'), 'backtest_jobs', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_backtest_jobs_workspace_id'), 'backtest_jobs', ['workspace_id'], unique=False)
    op.create_table('live_deployment_requests',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('broker_connection_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('deployment_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_deployment_requests_strategy_id'), 'live_deployment_requests', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_live_deployment_requests_workspace_id'), 'live_deployment_requests', ['workspace_id'], unique=False)
    op.create_table('paper_positions',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('size_units', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('open_ts', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_account_id'), 'paper_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_positions_strategy_id'), 'paper_positions', ['strategy_id'], unique=False)
    op.create_table('risk_events',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_event_type'), 'risk_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_risk_events_strategy_id'), 'risk_events', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_risk_events_workspace_id'), 'risk_events', ['workspace_id'], unique=False)
    op.create_table('strategy_rules',
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_rules_strategy_id'), 'strategy_rules', ['strategy_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('start_ts', sa.Float(), nullable=False),
    sa.Column('end_ts', sa.Float(), nullable=False),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('drawdown_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('robustness', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['backtest_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_job_id'), 'backtest_runs', ['job_id'], unique=False)
    op.create_table('backtest_metrics',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_metrics_run_id'), 'backtest_metrics', ['run_id'], unique=False)
    op.create_table('simulated_orders',
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('paper_account_id', sa.String(length=36), nullable=True),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('entry_ts', sa.Float(), nullable=False),
    sa.Column('exit_ts', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('size_units', sa.Float(), nullable=False),
    sa.Column('risk_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('reasons_entry', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasons_exit', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spread_cost', sa.Float(), nullable=False),
    sa.Column('slippage_cost', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('gross_pnl', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('pips', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulated_orders_paper_account_id'), 'simulated_orders', ['paper_account_id'], unique=False)
    op.create_index(op.f('ix_simulated_orders_run_id'), 'simulated_orders', ['run_id'], unique=False)
    op.create_index(op.f('ix_simulated_orders_strategy_id'), 'simulated_orders', ['strategy_id'], unique=False)
    op.create_table('simulated_fills',
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('fill_type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['simulated_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulated_fills_order_id'), 'simulated_fills', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulated_fills_order_id'), table_name='simulated_fills')
    op.drop_table('simulated_fills')
    op.drop_index(op.f('ix_simulated_orders_strategy_id'), table_name='simulated_orders')
    op.drop_index(op.f('ix_simulated_orders_run_id'), table_name='simulated_orders')
    op.drop_index(op.f('ix_simulated_orders_paper_account_id'), table_name='simulated_orders')
    op.drop_table('simulated_orders')
    op.drop_index(op.f('ix_backtest_metrics_run_id'), table_name='backtest_metrics')
    op.drop_table('backtest_metrics')
    op.drop_index(op.f('ix_backtest_runs_job_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_strategy_rules_strategy_id'), table_name='strategy_rules')
    op.drop_table('strategy_rules')
    op.drop_index(op.f('ix_risk_events_workspace_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_strategy_id'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_event_type'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_paper_positions_strategy_id'), table_name='paper_positions')
    op.drop_index(op.f('ix_paper_positions_account_id'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_live_deployment_requests_workspace_id'), table_name='live_deployment_requests')
    op.drop_index(op.f('ix_live_deployment_requests_strategy_id'), table_name='live_deployment_requests')
    op.drop_table('live_deployment_requests')
    op.drop_index(op.f('ix_backtest_jobs_workspace_id'), table_name='backtest_jobs')
    op.drop_index(op.f('ix_backtest_jobs_strategy_id'), table_name='backtest_jobs')
    op.drop_table('backtest_jobs')
    op.drop_index(op.f('ix_strategies_workspace_id'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_strategy_family'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_name'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_saved_chart_layouts_workspace_id'), table_name='saved_chart_layouts')
    op.drop_table('saved_chart_layouts')
    op.drop_index(op.f('ix_risk_profiles_workspace_id'), table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_index(op.f('ix_paper_accounts_workspace_id'), table_name='paper_accounts')
    op.drop_table('paper_accounts')
    op.drop_index(op.f('ix_market_data_sources_workspace_id'), table_name='market_data_sources')
    op.drop_table('market_data_sources')
    op.drop_index(op.f('ix_forex_symbols_workspace_id'), table_name='forex_symbols')
    op.drop_index(op.f('ix_forex_symbols_provider_symbol'), table_name='forex_symbols')
    op.drop_index(op.f('ix_forex_symbols_provider'), table_name='forex_symbols')
    op.drop_index(op.f('ix_forex_symbols_canonical'), table_name='forex_symbols')
    op.drop_table('forex_symbols')
    op.drop_index(op.f('ix_economic_events_workspace_id'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_event_time'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_currency'), table_name='economic_events')
    op.drop_index(op.f('ix_economic_events_country'), table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index(op.f('ix_broker_connections_workspace_id'), table_name='broker_connections')
    op.drop_table('broker_connections')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_workspace_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ticks_ts'), table_name='ticks')
    op.drop_index(op.f('ix_ticks_symbol'), table_name='ticks')
    op.drop_table('ticks')
    op.drop_index(op.f('ix_spreads_ts'), table_name='spreads')
    op.drop_index(op.f('ix_spreads_symbol'), table_name='spreads')
    op.drop_table('spreads')
    op.drop_table('candles')
    # ### end Alembic commands ###
